FROM node:alpine

WORKDIR /app

ADD package.json ./

RUN npm install

ADD eslint.config.js /app/eslint.config.js
ADD .prettierrc.json /app/.prettierrc.json
ADD index.html /app/index.html
ADD vite.config.js /app/vite.config.js
ADD vitest.config.js /app/vitest.config.js

ADD src /app/src
ADD public /app/public

RUN npm run build

EXPOSE 8080

CMD ["sh", "-c", "npm run preview -- --port ${PORT:-8080} --host"]