services:
  api:
    image: learnpass-api
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./backend/bin:/app/bin
      - ./backend/src:/app/src
    env_file:
      - backend/.env
  frontend:
    image: learnpass-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_PROXY_TARGET: http://api:3000
    ports:
      - 5173:5173
    volumes:
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public 

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    attach: false