services:
  api:
    image: learnpass-api
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app/src
    env_file:
      - backend/.env
  frontend:
    image: learnpass-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_PROXY_TARGET: http://api:3000
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public 

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    command: mongod --quiet --replSet rs0 --bind_ip_all
    healthcheck:
      test: |
        mongosh --quiet --eval "
          try { rs.status().ok } catch(e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongodb:27017' }] }) }
        "
      interval: 10s
      start_period: 10s